### ISSUE TITLE
Wrong spelling in Readme.md

### ISSUE THREAD

**Issue by s4-2** [senesh-deshan/Google-Hash-Code-2020#12]
**Before:**
- Simply the algorithm is about adding up the number of slices of the given Pizzas in reverse order. In latest updated version, after each completion repeats the same procedure with a skipping the  **_elemnt_** before the lastly considered element of the input array. This way leads to approaches considering more different combinations for each problem and gives the perfect solution.

**After**
+ Simply the algorithm is about adding up the number of slices of the given Pizzas in reverse order. In latest updated version, after each completion repeats the same procedure with a skipping the  **_element_** before the lastly considered element of the input array. This way leads to approaches considering more different combinations for each problem and gives the perfect solution.

**Comment by s4-2** [comment]
Hello, I am new so I don't know how to submit an issue. Though it is not a big issue but I think it will good if get corrected.

**Comment by senesh-deshan** [comment]
I believe you did nothing wrong here. I have merged your pull request. Thank you for your contribution.
